"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Database_1 = require("../src/creational/singleton/Database");
const Logistics_1 = require("../src/creational/factory-method/Logistics");
const Adapter_1 = require("../src/structural/adapter/Adapter");
const HomeTheater_1 = require("../src/structural/facade/HomeTheater");
const Payment_1 = require("../src/behavioral/strategy/Payment");
console.log("--- START GOF PATTERNS DEMO ---\n");
console.log("1. CREATIONAL: Singleton");
Database_1.Database.getInstance().query("SELECT * FROM products");
console.log("\n2. CREATIONAL: Factory Method");
new Logistics_1.RoadLogistics().planDelivery();
console.log("\n3. STRUCTURAL: Adapter");
new Adapter_1.PrinterAdapter().print("Звіт за квартал");
console.log("\n4. STRUCTURAL: Facade");
new HomeTheater_1.HomeTheaterFacade().watchMovie();
console.log("\n5. BEHAVIORAL: Strategy");
const cart = new Payment_1.ShoppingCart();
cart.setStrategy(new Payment_1.PayPalPayment());
cart.checkout(1200);
